// Encrypts the CV content + portrait into src/lib/cv-payload.ts.
//
// Usage:
//   SITE_PASSWORD="your-secret-phrase" node scripts/encrypt-cv.mjs
//
// Re-run this whenever you edit scripts/cv-source.json, replace
// src/assets/portrait.jpg, or change the passphrase. The passphrase itself
// is never written anywhere — only AES-GCM ciphertext ships in the site.

import { readFileSync, writeFileSync } from "node:fs";
import { randomBytes, pbkdf2Sync, createCipheriv } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const passphrase = process.env.SITE_PASSWORD;
if (!passphrase || passphrase.length < 8) {
  console.error("SITE_PASSWORD env var is required (min 8 characters).");
  process.exit(1);
}

const ITERATIONS = 600_000; // OWASP recommendation for PBKDF2-SHA256
const salt = randomBytes(16);
const key = pbkdf2Sync(passphrase, salt, ITERATIONS, 32, "sha256");

function encrypt(plaintext) {
  const iv = randomBytes(12);
  const cipher = createCipheriv("aes-256-gcm", key, iv);
  const body = Buffer.concat([cipher.update(plaintext), cipher.final()]);
  const tag = cipher.getAuthTag();
  // Web Crypto expects ciphertext and auth tag concatenated.
  return {
    iv: iv.toString("base64"),
    data: Buffer.concat([body, tag]).toString("base64"),
  };
}

const cvJson = readFileSync(join(root, "scripts/cv-source.json"), "utf8");
JSON.parse(cvJson); // fail fast on invalid JSON
const portrait = readFileSync(join(root, "src/assets/portrait.jpg"));

const cv = encrypt(Buffer.from(cvJson, "utf8"));
const pic = encrypt(portrait);

const out = `// GENERATED by scripts/encrypt-cv.mjs — do not edit by hand.
// Contains only AES-GCM ciphertext; useless without the passphrase.
export const CV_PAYLOAD = {
  v: 1,
  kdf: { salt: ${JSON.stringify(salt.toString("base64"))}, iterations: ${ITERATIONS} },
  cv: { iv: ${JSON.stringify(cv.iv)}, data: ${JSON.stringify(cv.data)} },
  portrait: {
    iv: ${JSON.stringify(pic.iv)},
    data: ${JSON.stringify(pic.data)},
    type: "image/jpeg",
  },
} as const;
`;

writeFileSync(join(root, "src/lib/cv-payload.ts"), out);
console.log(
  `Encrypted CV (${cvJson.length} B) + portrait (${portrait.length} B) -> src/lib/cv-payload.ts`,
);
