// Builds src/lib/cv-payload.ts from the CV content + portrait.
//
// Usage:
//   SITE_PASSWORD="your-secret-phrase" node scripts/encrypt-cv.mjs
//
// Two knobs, both optional — the build never fails because a secret is absent:
//
//   SITE_PASSWORD    when set (min 8 chars) the payload is AES-GCM encrypted
//                    and visitors must type the passphrase. When absent the
//                    payload ships "open" and the gate is bypassed.
//   CV_SOURCE_JSON   the CV content as raw JSON. Falls back to
//                    scripts/cv-source.json, and if that is missing too, to
//                    scripts/cv-placeholder.json (lorem ipsum).

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { randomBytes, pbkdf2Sync, createCipheriv } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const passphrase = process.env.SITE_PASSWORD?.trim();
const locked = Boolean(passphrase && passphrase.length >= 8);
if (passphrase && !locked) {
  console.warn("SITE_PASSWORD is shorter than 8 characters — ignoring it and shipping open.");
}

// ---------------------------------------------------------------- CV content
let cvJson;
let cvOrigin;
if (process.env.CV_SOURCE_JSON?.trim()) {
  cvJson = process.env.CV_SOURCE_JSON;
  cvOrigin = "CV_SOURCE_JSON env";
} else if (existsSync(join(root, "scripts/cv-source.json"))) {
  cvJson = readFileSync(join(root, "scripts/cv-source.json"), "utf8");
  cvOrigin = "scripts/cv-source.json";
} else {
  cvJson = readFileSync(join(root, "scripts/cv-placeholder.json"), "utf8");
  cvOrigin = "scripts/cv-placeholder.json (lorem ipsum)";
}
JSON.parse(cvJson); // fail fast on invalid JSON

// ------------------------------------------------------------------ portrait
// 1x1 transparent PNG stand-in when no portrait is available.
const PLACEHOLDER_PORTRAIT = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=",
  "base64",
);
const portraitPath = join(root, "src/assets/portrait.jpg");
const hasPortrait = existsSync(portraitPath);
const portrait = hasPortrait ? readFileSync(portraitPath) : PLACEHOLDER_PORTRAIT;
const portraitType = hasPortrait ? "image/jpeg" : "image/png";

// ----------------------------------------------------------------- packaging
const ITERATIONS = 600_000; // OWASP recommendation for PBKDF2-SHA256
const salt = randomBytes(16);
const key = locked ? pbkdf2Sync(passphrase, salt, ITERATIONS, 32, "sha256") : null;

function pack(plaintext) {
  const bytes = Buffer.isBuffer(plaintext) ? plaintext : Buffer.from(plaintext, "utf8");
  if (!locked) {
    // Open mode: no key exists, so the bytes ship as plain base64.
    return { iv: "", data: bytes.toString("base64") };
  }
  const iv = randomBytes(12);
  const cipher = createCipheriv("aes-256-gcm", key, iv);
  const body = Buffer.concat([cipher.update(bytes), cipher.final()]);
  const tag = cipher.getAuthTag();
  // Web Crypto expects ciphertext and auth tag concatenated.
  return {
    iv: iv.toString("base64"),
    data: Buffer.concat([body, tag]).toString("base64"),
  };
}

const cv = pack(cvJson);
const pic = pack(portrait);

const out = `// GENERATED by scripts/encrypt-cv.mjs — do not edit by hand.
// locked: true  -> AES-GCM ciphertext, useless without the passphrase.
// locked: false -> plain base64, no passphrase was configured at build time.
export const CV_PAYLOAD = {
  v: 1,
  locked: ${locked},
  kdf: { salt: ${JSON.stringify(salt.toString("base64"))}, iterations: ${ITERATIONS} },
  cv: { iv: ${JSON.stringify(cv.iv)}, data: ${JSON.stringify(cv.data)} },
  portrait: {
    iv: ${JSON.stringify(pic.iv)},
    data: ${JSON.stringify(pic.data)},
    type: ${JSON.stringify(portraitType)},
  },
} as const;
`;

writeFileSync(join(root, "src/lib/cv-payload.ts"), out);
console.log(
  `${locked ? "Encrypted" : "Packed (OPEN — no passphrase)"} CV from ${cvOrigin} ` +
    `(${cvJson.length} B) + portrait (${portrait.length} B) -> src/lib/cv-payload.ts`,
);
if (!locked) {
  console.warn("No SITE_PASSWORD set: the site will be publicly readable, gate bypassed.");
}
